import { AsyncSection } from "../components/common/AsyncSection";
import { Button } from "../components/common/Button";
import { Card } from "../components/common/Card";
import { EmptyState } from "../components/common/EmptyState";
import { PageShell } from "../components/common/PageShell";
import { SkeletonKpiRow, SkeletonRows } from "../components/common/Skeleton";
import { SummaryCard } from "../components/dashboard/SummaryCard";
import { useAsync } from "../hooks/useAsync";
import { deleteAlert, listAlerts, markAlertRead, markAllAlertsRead } from "../services/planning.service";
import type { Alert } from "../types/models";
import { formatDate } from "../utils/format";

const SEVERITY_ICONS: Record<Alert["severity"], string> = {
  info: "ℹ️",
  warning: "⚠️",
  critical: "🚨",
};

export default function AlertsPage() {
  const alerts = useAsync(() => listAlerts(), [], "לא הצלחנו לטעון את ההתראות");

  async function readAll() {
    await markAllAlertsRead();
    alerts.reload();
  }

  async function read(alert: Alert) {
    await markAlertRead(alert.id);
    alerts.reload();
  }

  // Dismissing an alert is not destructive — it is regenerated by the scanner
  // while the condition still holds — so it needs no confirmation step.
  async function remove(alert: Alert) {
    await deleteAlert(alert.id);
    alerts.reload();
  }

  const unread = alerts.data?.filter((a) => !a.isRead).length ?? 0;

  return (
    <PageShell
      toolbar={
        unread > 0 ? <Button variant="outline" onClick={readAll}>סימון הכל כנקרא ✓</Button> : undefined
      }
      summary={
        <AsyncSection
          resource={alerts}
          errorTitle="לא הצלחנו לטעון את סיכום ההתראות"
          skeleton={<SkeletonKpiRow count={3} label="טוען סיכום" />}
        >
          {(rows) => (
            <div className="kpi-row">
              <SummaryCard
                label="לא נקראו"
                value={String(unread)}
                icon="🔔"
                tone={unread > 0 ? "warning" : "success"}
                accent={unread > 0}
              />
              <SummaryCard
                label="דחופות"
                value={String(rows.filter((a) => a.severity === "critical").length)}
                icon="🚨"
                tone="danger"
              />
              <SummaryCard label="סה״כ התראות" value={String(rows.length)} icon="📋" />
            </div>
          )}
        </AsyncSection>
      }
    >
      <AsyncSection
        resource={alerts}
        errorTitle="לא הצלחנו לטעון את ההתראות"
        skeleton={<SkeletonRows rows={3} label="טוען התראות" />}
        isEmpty={(rows) => rows.length === 0}
        emptyState={
          <Card>
            <EmptyState icon="🚨" title="אין התראות" hint="התראות על חריגות תקציב, חיובים גבוהים והלוואות יקרות יופיעו כאן" />
          </Card>
        }
      >
        {(rows) => (
          <div className="alerts-list">
            {rows.map((alert) => (
              <Card key={alert.id} className={`alert-card severity-${alert.severity} ${alert.isRead ? "alert-read" : ""}`}>
                <div className="alert-row">
                  <span className="alert-icon">{SEVERITY_ICONS[alert.severity]}</span>
                  <div className="alert-body">
                    <div className="alert-title">{alert.title}</div>
                    <div className="alert-message text-muted">{alert.message}</div>
                    <div className="alert-date text-muted">{formatDate(alert.createdAt)}</div>
                  </div>
                  <span className="row-actions">
                    {!alert.isRead && (
                      <Button size="sm" variant="ghost" onClick={() => read(alert)} aria-label={`סימון "${alert.title}" כנקרא`}>
                        ✓
                      </Button>
                    )}
                    <Button size="sm" variant="ghost" onClick={() => remove(alert)} aria-label={`מחיקת "${alert.title}"`}>
                      🗑️
                    </Button>
                  </span>
                </div>
              </Card>
            ))}
          </div>
        )}
      </AsyncSection>
    </PageShell>
  );
}
